name: Train Image Classification
id: 5e968de0-d172-4526-a319-0d8ca5bd4eb6
version: 0.0.1.1
isDeterministic: true
category: Image Classification
description: Train image classification model from scratch or finetune it.
inputs:
- name: Untrained model
  type: ModelDirectory
  port: True
  description: Untrained or pretrained model.
- name: Train data path
  type: ImageDirectory
  port: True
  description: Train data path.
- name: Valid data path
  type: ImageDirectory
  port: True
  description: Valid data path.
- name: Epochs
  type: Int
  default: 40
  description: Epochs.
- name: Batch size
  type: Int
  default: 128
  description: Batch size.
- name: Learning rate
  type: Float
  default: 0.001
  description: Learning rate.
- name: Random seed
  type: Int
  default: 1
  description: Random seed.
- name: Patience
  type: Int
  default: 3
  description: Patience.
outputs:
- name: Saved model path
  type: ModelDirectory
  description: Saved model path.
implementation:
  container:
    runConfig:
      baseDockerImage: mcr.microsoft.com/azureml/base-gpu:intelmpi2018.3-cuda10.0-cudnn7-ubuntu16.04
      gpuSupport: True
    conda:
      name: project_environment
      channels:
      - defaults
      dependencies:
      - python=3.6.8
      - pip:
        - azureml-defaults
        - azureml-designer-core[image]==0.0.25.*
        - azureml-designer-model==0.1.20191126.2
        - torch==1.3
        - torchvision==0.4.1
        - fire==0.1.3
        - git+https://github.com/chjinche/CustomModules-1.git@master#subdirectory=azureml-custom-module-examples/image-classification
    command:
    - python
    - -m
    - imageclassification.train_image_classification
    args:
    - --input-model-path
    - inputValue: Untrained model
    - --train-data-path
    - inputValue: Train data path
    - --valid-data-path
    - inputValue: Valid data path
    - --epochs
    - inputValue: Epochs
    - --batch-size
    - inputValue: Batch size
    - --learning-rate
    - inputValue: Learning rate
    - --random-seed
    - inputValue: Random seed
    - --patience
    - inputValue: Patience
    - --save-model-path
    - outputPath: Saved model path
